<?php
function listingInstructions()
{
?>
<p class="listing">To have your school listed in this directory, or to revise your listing,
please use the <a href="schoolUpdate.php">school update</a> or <a
	href="instructorUpdate.php">instructor update</a> form. Or complete and
mail the <a href="images/aero_directory_application.pdf">the aerobatic
flight school directory application</a>.</p>
<?php
}

function disclaimer()
{
   echo '<div class="disclaimer">The following are flight schools, and/or individuals, that have requested to be listed here as an aerobatic flight school or instructor. IAC does not endorse or recommend any of the schools listed or the qualifications, experience or expertise of any Aerobatic Instructors.</div>'; 
}
?>