<?php
$dbprefix='wbreezec_';
$dbhost = 'localhost';
$dbuser = 'sitePHP';
$dbpasswd = 'goN7l0xmRoTa/v2aAa0E';
$dbname = 'schools';
$table_prefix = '';
$baseURL = '/schools/';

$debug=false;
// debug action can be logfile name, or "echo"
$debug_action="/home/wbreezec/log/debug.log";
// email action can be logfile name, or "echo" or "mail"
// $email_action="/home/dcl/Documents/ws.iacusn/AerobaticSchools/log/email.log";
$email_action='mail';

// web service administrator
$admin_email = "admin@iacusn.org";

// IAC schools liason
$schools_email = 'lynn.bowes@hotmail.com';
$schools_name = 'Lynn Bowes';

/*
   Copyright 2009 International Aerobatic Club, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
?>
